resources:
  - deployments/email-service-deployment.yaml
  - deployments/notification-service-deployment.yaml
  - deployments/sms-service-deployment.yaml
  - deployments/user-service-deployment.yaml
  - deployments/order-service-deployment.yaml
  - deployments/driver-service-deployment.yaml
  - deployments/delivery-service-deployment.yaml
  - deployments/payment-service-deployment.yaml
  - deployments/frontend-service-deployment.yaml
  - rabbitmq/rabbitmq.yaml
  - ingress/ingress.yaml

configMapGenerator:
  - name: email-service-env
    envs:
      - configs/email-service.env
  - name: notification-service-env
    envs:
      - configs/notification-service.env
  - name: sms-service-env
    envs:
      - configs/sms-service.env
  - name: user-service-env
    envs:
      - configs/user-service.env
  - name: order-service-env
    envs:
      - configs/order-service.env
  - name: payment-service-env
    envs:
      - configs/payment-service.env
  - name: driver-service-env
    envs:
      - configs/driver-service.env
  - name: delivery-service-env
    envs:
      - configs/delivery-service.env

generatorOptions:
  disableNameSuffixHash: true
