version: '3.8'

services:
  order-service:
    build: .
    ports:
      - "5000:5000"
    environment:
    - .env
    depends_on:
      - mongo
    networks:
      - order-management-network
    volumes:
      - .:/app
    restart: unless-stopped

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    networks:
      - order-management-network
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped


networks:
  order-management-network:
    external: true

volumes:
  mongo_data:
