version: '3.8'
services:
  payment-service:
    build: .
    container_name: payment-service
    ports:
      - "5002:5002"
    env_file:
      - .env
    networks:
      - order-management-network

networks:
  order-management-network:
    external: true