# three node (two workers + one control-plane) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.30.6
  extraPortMappings:
    - containerPort: 80
      hostPort: 8080
      listenAddress: "0.0.0.0"
      protocol: udp
    - containerPort: 3000
      hostPort: 33000
      listenAddress: "0.0.0.0"
      protocol: tcp
    - containerPort: 443
      hostPort: 4443
      listenAddress: "0.0.0.0"
      protocol: tcp
    - containerPort: 8080
      hostPort: 38080
      listenAddress: "0.0.0.0"
      protocol: tcp

- role: worker
  image: kindest/node:v1.30.6

- role: worker
  image: kindest/node:v1.30.6
