apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend-service
          image: nmdra/frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
spec:
  selector:
    app: frontend-service
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
