apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: nmdra/notification-service
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: notification-service-env
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: notification-service-env
                  key: DB_NAME
            - name: DB_PASS
              valueFrom:
                configMapKeyRef:
                  name: notification-service-env
                  key: DB_PASS
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: notification-service-env
                  key: DB_USER
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: notification-service-env
                  key: PORT
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: notification-service-env
                  key: RABBITMQ_URL
      restartPolicy: Always
      hostname: notification-service

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: default
spec:
  selector:
    app: notification-service
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
