name: Build and Push Images

on:
  # push:
  #   # branches:
  #   #   - main
  #   tags:
  #     - 'v*.*.*'
  workflow_dispatch:

jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push
        uses: docker/bake-action@v6
        with:
          push: true
          files: |
            ./docker-bake.hcl
          set: |
            *.labels.org.opencontainers.image.revision=${{ github.sha }}
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
